[2025-03-30T16:36:07.176+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T16:36:07.195+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.add_data_to_postgres scheduled__2025-03-30T06:00:00+00:00 [queued]>
[2025-03-30T16:36:07.205+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.add_data_to_postgres scheduled__2025-03-30T06:00:00+00:00 [queued]>
[2025-03-30T16:36:07.205+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-30T16:36:07.220+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): add_data_to_postgres> on 2025-03-30 06:00:00+00:00
[2025-03-30T16:36:07.228+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'add_data_to_postgres', 'scheduled__2025-03-30T06:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpa8p6jh3g']
[2025-03-30T16:36:07.231+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask add_data_to_postgres
[2025-03-30T16:36:07.235+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=847) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T16:36:07.236+0000] {standard_task_runner.py:72} INFO - Started process 848 to run task
[2025-03-30T16:36:07.285+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.add_data_to_postgres scheduled__2025-03-30T06:00:00+00:00 [running]> on host 2b1913b6b87b
[2025-03-30T16:36:07.370+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='add_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T06:00:00+00:00'
[2025-03-30T16:36:07.372+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T16:36:07.434+0000] {main.py:217} INFO - Dữ liệu đã được chèn vào PostgreSQL.
[2025-03-30T16:36:07.435+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-30T16:36:07.447+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T16:36:07.448+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=add_data_to_postgres, run_id=scheduled__2025-03-30T06:00:00+00:00, execution_date=20250330T060000, start_date=20250330T163607, end_date=20250330T163607
[2025-03-30T16:36:07.492+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T16:36:07.520+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T16:36:07.524+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
